# Miniflux Exporter Configuration Example
# Copy this file to config.yaml and update with your settings

# ==============================================================================
# Miniflux Connection (Required)
# ==============================================================================

# Your Miniflux instance URL (without /v1/ suffix)
miniflux_url: https://miniflux.example.com

# Your Miniflux API key
# Get it from: Settings -> API Keys -> Create a new API key
api_key: your_api_key_here

# ==============================================================================
# Output Configuration
# ==============================================================================

# Directory where exported articles will be saved
output_dir: miniflux_articles

# Organize articles by feed (creates a folder for each feed)
organize_by_feed: true

# Organize articles by category (creates a folder for each category)
# If both organize_by_category and organize_by_feed are true,
# the structure will be: category/feed/articles
organize_by_category: false

# ==============================================================================
# Filters (Optional)
# ==============================================================================

# Filter by article status
# Options: null (all articles), "read", "unread"
filter_status: null

# Filter by starred status
# Options: null (all articles), true (only starred), false (only non-starred)
filter_starred: null

# ==============================================================================
# Filename Configuration
# ==============================================================================

# Template for article filenames
# Available variables: {date}, {id}, {title}
# Examples:
#   "{date}_{title}"        -> 2024-01-15_Article_Title.md
#   "{id}_{title}"          -> 12345_Article_Title.md
#   "{date}_{id}"           -> 2024-01-15_12345.md
#   "{title}"               -> Article_Title.md
filename_format: "{date}_{title}"

# ==============================================================================
# Export Options
# ==============================================================================

# Number of articles to fetch per batch (1-1000)
# Higher values are faster but use more memory
batch_size: 100

# Include YAML front matter with metadata in each file
include_metadata: true

# Save a JSON file with all articles' metadata
save_json_metadata: true

# ==============================================================================
# Markdown Conversion Options
# ==============================================================================

markdown_options:
  # Ignore links in the HTML content
  ignore_links: false

  # Ignore images in the HTML content
  ignore_images: false

  # Maximum width for text wrapping (0 = no wrapping)
  body_width: 0

  # Skip internal anchor links
  skip_internal_links: false

# ==============================================================================
# Advanced Examples
# ==============================================================================

# Example 1: Export only unread articles
# filter_status: unread
# filter_starred: null

# Example 2: Export only starred articles
# filter_status: null
# filter_starred: true

# Example 3: Export unread starred articles
# filter_status: unread
# filter_starred: true

# Example 4: Organize by category and feed
# organize_by_feed: true
# organize_by_category: true

# Example 5: Simple filenames (avoid long titles)
# filename_format: "{date}_{id}"

# Example 6: Minimize file sizes
# markdown_options:
#   ignore_links: true
#   ignore_images: true
